apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Datagrid Prometeus metrics exposed
  labels:
    app: datagrid-service
    application: datagrid-service
    template: datagrid-service
    metrics: datagrid
  name: datagrid-app-metrics
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 9779
  selector:
    deploymentConfig: datagrid-service
  sessionAffinity: None
  type: ClusterIP


